language: scala
scala:
- 2.11.8
jdk:
  - oraclejdk8
dist: trusty
addons:
  sonarqube:
    organization: "sonarsource"
script:
  - mvn clean test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar